# Generated by Django 5.1.4 on 2025-10-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='option',
            table='Option',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='Topic',
        ),
    ]
