# Generated by Django 6.0.2 on 2026-03-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_alter_option_table_alter_question_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
    ]
