# Generated by Django 5.1.4 on 2025-10-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstApp', '0003_rename_gmail_user_email'),
        ('quizApp', '0002_alter_option_table_alter_question_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quizApp.option')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quizApp.quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_details', to='firstApp.user')),
            ],
            options={
                'db_table': 'QuizDetail',
            },
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quizApp.quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='firstApp.user')),
            ],
            options={
                'db_table': 'QuizProgress',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quiz_progress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='testApp.quizprogress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='firstApp.user')),
            ],
            options={
                'db_table': 'UserScore',
            },
        ),
    ]
