# Generated by Django 6.0.2 on 2026-03-12 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='completion_time',
            field=models.IntegerField(default=0, help_text='Completion time in seconds'),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
