# Generated by Django 5.1.4 on 2025-10-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
