# Generated by Django 5.1.4 on 2025-10-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_user_gmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gmail',
            new_name='email',
        ),
    ]
