# Generated by Django 5.1.4 on 2026-01-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_rename_gmail_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
