# Generated by Django 5.1.4 on 2026-01-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_user_verified'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='BlackListedToken',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
